### ISSUE TITLE
allow for functions into a class

### ISSUE THREAD

**Issue by ignatandrei** [JasonBock/PartiallyApplied#9]
For the moment, I see that it is applied to static
Could you make an attribute that we can apply to function of a class ?

**Comment by JasonBock** [comment]
This works with methods on objects:

```
public class Functions
{
  public int Multiply(int a, int b) => a * b;
}

var functions = new Functions();
var triple = Partially.Apply(functions.Multiply, 3);
Console.Out.WriteLine(triple(4));
```

This should print out `12`.

**Comment by JasonBock** [comment]
I also updated the Quickstart to reflect this.
